Bump Rust to version 1.77
When trying to build rowan we get this error

    error: package `rowan v0.15.16` cannot be built because
    it requires rustc 1.77.0 or newer, while the currently active rustc
    version is 1.75.0

So let's upgrade to 1.77 to allow us to build rowan.