Bump Rust to version 1.75
When trying to build embedded-hal-async we get this error

    error: package `embedded-hal-async v1.0.0` cannot be built because
    it requires rustc 1.75 or newer, while the currently active rustc
    version is 1.74.1

So let's upgrade to 1.75 to allow us to build embedded-hal-async.

Signed-off-by: Alistair Francis <alistair.francis@wdc.com>